---
- name: ServiceCore & Zabbix Sync Automation
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Run Python Sync Script
      ansible.builtin.command: >
        python3 sc_zabbix_sync.py
      environment:
        SC_API_URL: "{{ sc_url }}"
        SC_API_TOKEN: "{{ sc_token }}"
        ZBX_API_URL: "{{ zbx_url }}"
        ZBX_API_TOKEN: "{{ zbx_token }}"
        
        # Ozel ID yapılandırmaları
        SC_CLOSED_STATUS_IDS: "{{ sc_closed_ids | default('5,6') }}"
        SC_REOPEN_STATUS_ID: "{{ sc_reopen_id | default('1') }}"
        SC_EVENT_ID_FIELD_ID: "{{ sc_event_field_id | default('62128') }}"
        LOOKBACK_MINUTES: "{{ lookback_min | default('60') }}"
      register: output

    - name: Print Script Output
      debug:
        msg: "{{ output.stdout_lines }}"