---
- name: ServiceCore & Zabbix Sync Automation (Safe Mode)
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Run Python Sync Script
      ansible.builtin.command: >
        python3 sc_zabbix_sync.py
      environment:
        SC_API_URL: "{{ sc_url }}"
        SC_API_TOKEN: "{{ sc_token }}"
        ZBX_API_URL: "{{ zbx_url }}"
        ZBX_API_TOKEN: "{{ zbx_token }}"
        
        # --- YASAKLI STATÜLER ---
        # 2:  Kapatılanlar
        # 46: Tamamlanmış
        # 83: Çözüldü
        # 94: İptal Edildi
        # 65: Ertelenen
        SC_BAD_STATUS_IDS: "2, 46, 83, 94, 65"
        
        # --- HEDEF STATÜ ---
        # Kurtarılan ticket hangi statüye gelsin? (78: Atandı)
        SC_TARGET_STATUS_ID: "78"
        
      register: output
      ignore_errors: yes

    - name: Print Script Output
      debug:
        msg: "{{ output.stdout_lines }}"
